// Generated by gencpp from file birl_sim_examples/Add_Gazebo_ModelResponse.msg
// DO NOT EDIT!


#ifndef BIRL_SIM_EXAMPLES_MESSAGE_ADD_GAZEBO_MODELRESPONSE_H
#define BIRL_SIM_EXAMPLES_MESSAGE_ADD_GAZEBO_MODELRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace birl_sim_examples
{
template <class ContainerAllocator>
struct Add_Gazebo_ModelResponse_
{
  typedef Add_Gazebo_ModelResponse_<ContainerAllocator> Type;

  Add_Gazebo_ModelResponse_()
    : load_status()  {
    }
  Add_Gazebo_ModelResponse_(const ContainerAllocator& _alloc)
    : load_status(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _load_status_type;
  _load_status_type load_status;




  typedef boost::shared_ptr< ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Add_Gazebo_ModelResponse_

typedef ::birl_sim_examples::Add_Gazebo_ModelResponse_<std::allocator<void> > Add_Gazebo_ModelResponse;

typedef boost::shared_ptr< ::birl_sim_examples::Add_Gazebo_ModelResponse > Add_Gazebo_ModelResponsePtr;
typedef boost::shared_ptr< ::birl_sim_examples::Add_Gazebo_ModelResponse const> Add_Gazebo_ModelResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace birl_sim_examples

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b63f986befa7a8858821abe317753048";
  }

  static const char* value(const ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb63f986befa7a885ULL;
  static const uint64_t static_value2 = 0x8821abe317753048ULL;
};

template<class ContainerAllocator>
struct DataType< ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "birl_sim_examples/Add_Gazebo_ModelResponse";
  }

  static const char* value(const ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
std_msgs/Bool load_status\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Bool\n\
bool data\n\
";
  }

  static const char* value(const ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.load_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Add_Gazebo_ModelResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::birl_sim_examples::Add_Gazebo_ModelResponse_<ContainerAllocator>& v)
  {
    s << indent << "load_status: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.load_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIRL_SIM_EXAMPLES_MESSAGE_ADD_GAZEBO_MODELRESPONSE_H
