// Generated by gencpp from file birl_sim_examples/Add_Gazebo_ModelRequest.msg
// DO NOT EDIT!


#ifndef BIRL_SIM_EXAMPLES_MESSAGE_ADD_GAZEBO_MODELREQUEST_H
#define BIRL_SIM_EXAMPLES_MESSAGE_ADD_GAZEBO_MODELREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>
#include <geometry_msgs/Pose.h>
#include <std_msgs/String.h>

namespace birl_sim_examples
{
template <class ContainerAllocator>
struct Add_Gazebo_ModelRequest_
{
  typedef Add_Gazebo_ModelRequest_<ContainerAllocator> Type;

  Add_Gazebo_ModelRequest_()
    : model_name()
    , model_pose()
    , model_reference_frame()  {
    }
  Add_Gazebo_ModelRequest_(const ContainerAllocator& _alloc)
    : model_name(_alloc)
    , model_pose(_alloc)
    , model_reference_frame(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _model_name_type;
  _model_name_type model_name;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _model_pose_type;
  _model_pose_type model_pose;

   typedef  ::std_msgs::String_<ContainerAllocator>  _model_reference_frame_type;
  _model_reference_frame_type model_reference_frame;




  typedef boost::shared_ptr< ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Add_Gazebo_ModelRequest_

typedef ::birl_sim_examples::Add_Gazebo_ModelRequest_<std::allocator<void> > Add_Gazebo_ModelRequest;

typedef boost::shared_ptr< ::birl_sim_examples::Add_Gazebo_ModelRequest > Add_Gazebo_ModelRequestPtr;
typedef boost::shared_ptr< ::birl_sim_examples::Add_Gazebo_ModelRequest const> Add_Gazebo_ModelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace birl_sim_examples

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd9e795de7af30bcc513d8670bda1883";
  }

  static const char* value(const ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd9e795de7af30bcULL;
  static const uint64_t static_value2 = 0xc513d8670bda1883ULL;
};

template<class ContainerAllocator>
struct DataType< ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "birl_sim_examples/Add_Gazebo_ModelRequest";
  }

  static const char* value(const ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
std_msgs/String model_name\n\
\n\
\n\
geometry_msgs/Pose model_pose\n\
\n\
\n\
std_msgs/String model_reference_frame\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.model_name);
      stream.next(m.model_pose);
      stream.next(m.model_reference_frame);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Add_Gazebo_ModelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::birl_sim_examples::Add_Gazebo_ModelRequest_<ContainerAllocator>& v)
  {
    s << indent << "model_name: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.model_name);
    s << indent << "model_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.model_pose);
    s << indent << "model_reference_frame: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.model_reference_frame);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIRL_SIM_EXAMPLES_MESSAGE_ADD_GAZEBO_MODELREQUEST_H
