// Generated by gencpp from file birl_sim_examples/Go_To_Position.msg
// DO NOT EDIT!


#ifndef BIRL_SIM_EXAMPLES_MESSAGE_GO_TO_POSITION_H
#define BIRL_SIM_EXAMPLES_MESSAGE_GO_TO_POSITION_H

#include <ros/service_traits.h>


#include <birl_sim_examples/Go_To_PositionRequest.h>
#include <birl_sim_examples/Go_To_PositionResponse.h>


namespace birl_sim_examples
{

struct Go_To_Position
{

typedef Go_To_PositionRequest Request;
typedef Go_To_PositionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Go_To_Position
} // namespace birl_sim_examples


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::birl_sim_examples::Go_To_Position > {
  static const char* value()
  {
    return "d6d31042fd9aa19888cf6a8cca49baf3";
  }

  static const char* value(const ::birl_sim_examples::Go_To_Position&) { return value(); }
};

template<>
struct DataType< ::birl_sim_examples::Go_To_Position > {
  static const char* value()
  {
    return "birl_sim_examples/Go_To_Position";
  }

  static const char* value(const ::birl_sim_examples::Go_To_Position&) { return value(); }
};


// service_traits::MD5Sum< ::birl_sim_examples::Go_To_PositionRequest> should match 
// service_traits::MD5Sum< ::birl_sim_examples::Go_To_Position > 
template<>
struct MD5Sum< ::birl_sim_examples::Go_To_PositionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::birl_sim_examples::Go_To_Position >::value();
  }
  static const char* value(const ::birl_sim_examples::Go_To_PositionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::birl_sim_examples::Go_To_PositionRequest> should match 
// service_traits::DataType< ::birl_sim_examples::Go_To_Position > 
template<>
struct DataType< ::birl_sim_examples::Go_To_PositionRequest>
{
  static const char* value()
  {
    return DataType< ::birl_sim_examples::Go_To_Position >::value();
  }
  static const char* value(const ::birl_sim_examples::Go_To_PositionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::birl_sim_examples::Go_To_PositionResponse> should match 
// service_traits::MD5Sum< ::birl_sim_examples::Go_To_Position > 
template<>
struct MD5Sum< ::birl_sim_examples::Go_To_PositionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::birl_sim_examples::Go_To_Position >::value();
  }
  static const char* value(const ::birl_sim_examples::Go_To_PositionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::birl_sim_examples::Go_To_PositionResponse> should match 
// service_traits::DataType< ::birl_sim_examples::Go_To_Position > 
template<>
struct DataType< ::birl_sim_examples::Go_To_PositionResponse>
{
  static const char* value()
  {
    return DataType< ::birl_sim_examples::Go_To_Position >::value();
  }
  static const char* value(const ::birl_sim_examples::Go_To_PositionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BIRL_SIM_EXAMPLES_MESSAGE_GO_TO_POSITION_H
