// Generated by gencpp from file birl_sim_examples/Gripper_MoveRequest.msg
// DO NOT EDIT!


#ifndef BIRL_SIM_EXAMPLES_MESSAGE_GRIPPER_MOVEREQUEST_H
#define BIRL_SIM_EXAMPLES_MESSAGE_GRIPPER_MOVEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Bool.h>

namespace birl_sim_examples
{
template <class ContainerAllocator>
struct Gripper_MoveRequest_
{
  typedef Gripper_MoveRequest_<ContainerAllocator> Type;

  Gripper_MoveRequest_()
    : gripper_desired_flag()  {
    }
  Gripper_MoveRequest_(const ContainerAllocator& _alloc)
    : gripper_desired_flag(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Bool_<ContainerAllocator>  _gripper_desired_flag_type;
  _gripper_desired_flag_type gripper_desired_flag;




  typedef boost::shared_ptr< ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator> const> ConstPtr;

}; // struct Gripper_MoveRequest_

typedef ::birl_sim_examples::Gripper_MoveRequest_<std::allocator<void> > Gripper_MoveRequest;

typedef boost::shared_ptr< ::birl_sim_examples::Gripper_MoveRequest > Gripper_MoveRequestPtr;
typedef boost::shared_ptr< ::birl_sim_examples::Gripper_MoveRequest const> Gripper_MoveRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace birl_sim_examples

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "871caa371d500d7fa688824bad2884cb";
  }

  static const char* value(const ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x871caa371d500d7fULL;
  static const uint64_t static_value2 = 0xa688824bad2884cbULL;
};

template<class ContainerAllocator>
struct DataType< ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "birl_sim_examples/Gripper_MoveRequest";
  }

  static const char* value(const ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
std_msgs/Bool gripper_desired_flag\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Bool\n\
bool data\n\
";
  }

  static const char* value(const ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gripper_desired_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Gripper_MoveRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::birl_sim_examples::Gripper_MoveRequest_<ContainerAllocator>& v)
  {
    s << indent << "gripper_desired_flag: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.gripper_desired_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BIRL_SIM_EXAMPLES_MESSAGE_GRIPPER_MOVEREQUEST_H
