(cl:defpackage example_smach-srv
  (:use )
  (:export
   "ADDFOURINTS"
   "<ADDFOURINTS-REQUEST>"
   "ADDFOURINTS-REQUEST"
   "<ADDFOURINTS-RESPONSE>"
   "ADDFOURINTS-RESPONSE"
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "ADDTHREEINTS"
   "<ADDTHREEINTS-REQUEST>"
   "ADDTHREEINTS-REQUEST"
   "<ADDTHREEINTS-RESPONSE>"
   "ADDTHREEINTS-RESPONSE"
  ))

