// Generated by gencpp from file force_controller/forceControlResponse.msg
// DO NOT EDIT!


#ifndef FORCE_CONTROLLER_MESSAGE_FORCECONTROLRESPONSE_H
#define FORCE_CONTROLLER_MESSAGE_FORCECONTROLRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace force_controller
{
template <class ContainerAllocator>
struct forceControlResponse_
{
  typedef forceControlResponse_<ContainerAllocator> Type;

  forceControlResponse_()
    : output(0)  {
    }
  forceControlResponse_(const ContainerAllocator& _alloc)
    : output(0)  {
  (void)_alloc;
    }



   typedef int32_t _output_type;
  _output_type output;




  typedef boost::shared_ptr< ::force_controller::forceControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::force_controller::forceControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct forceControlResponse_

typedef ::force_controller::forceControlResponse_<std::allocator<void> > forceControlResponse;

typedef boost::shared_ptr< ::force_controller::forceControlResponse > forceControlResponsePtr;
typedef boost::shared_ptr< ::force_controller::forceControlResponse const> forceControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::force_controller::forceControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::force_controller::forceControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace force_controller

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'force_controller': ['/home/ai05/ros_ws/src/birl_baxter_controllers/force_controller/msg'], 'baxter_core_msgs': ['/home/ai05/ros_ws/src/baxter_common/baxter_core_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::force_controller::forceControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::force_controller::forceControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::force_controller::forceControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::force_controller::forceControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::force_controller::forceControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::force_controller::forceControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::force_controller::forceControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5fc6b37f5643970fe87c91f31f11e4a";
  }

  static const char* value(const ::force_controller::forceControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5fc6b37f5643970ULL;
  static const uint64_t static_value2 = 0xfe87c91f31f11e4aULL;
};

template<class ContainerAllocator>
struct DataType< ::force_controller::forceControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "force_controller/forceControlResponse";
  }

  static const char* value(const ::force_controller::forceControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::force_controller::forceControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
int32 output\n\
\n\
";
  }

  static const char* value(const ::force_controller::forceControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::force_controller::forceControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct forceControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::force_controller::forceControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::force_controller::forceControlResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<int32_t>::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FORCE_CONTROLLER_MESSAGE_FORCECONTROLRESPONSE_H
