// Generated by gencpp from file force_controller/forceControl.msg
// DO NOT EDIT!


#ifndef FORCE_CONTROLLER_MESSAGE_FORCECONTROL_H
#define FORCE_CONTROLLER_MESSAGE_FORCECONTROL_H

#include <ros/service_traits.h>


#include <force_controller/forceControlRequest.h>
#include <force_controller/forceControlResponse.h>


namespace force_controller
{

struct forceControl
{

typedef forceControlRequest Request;
typedef forceControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct forceControl
} // namespace force_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::force_controller::forceControl > {
  static const char* value()
  {
    return "33800c3c3d1a1e0744d81c70e60d4c00";
  }

  static const char* value(const ::force_controller::forceControl&) { return value(); }
};

template<>
struct DataType< ::force_controller::forceControl > {
  static const char* value()
  {
    return "force_controller/forceControl";
  }

  static const char* value(const ::force_controller::forceControl&) { return value(); }
};


// service_traits::MD5Sum< ::force_controller::forceControlRequest> should match 
// service_traits::MD5Sum< ::force_controller::forceControl > 
template<>
struct MD5Sum< ::force_controller::forceControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::force_controller::forceControl >::value();
  }
  static const char* value(const ::force_controller::forceControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::force_controller::forceControlRequest> should match 
// service_traits::DataType< ::force_controller::forceControl > 
template<>
struct DataType< ::force_controller::forceControlRequest>
{
  static const char* value()
  {
    return DataType< ::force_controller::forceControl >::value();
  }
  static const char* value(const ::force_controller::forceControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::force_controller::forceControlResponse> should match 
// service_traits::MD5Sum< ::force_controller::forceControl > 
template<>
struct MD5Sum< ::force_controller::forceControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::force_controller::forceControl >::value();
  }
  static const char* value(const ::force_controller::forceControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::force_controller::forceControlResponse> should match 
// service_traits::DataType< ::force_controller::forceControl > 
template<>
struct DataType< ::force_controller::forceControlResponse>
{
  static const char* value()
  {
    return DataType< ::force_controller::forceControl >::value();
  }
  static const char* value(const ::force_controller::forceControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FORCE_CONTROLLER_MESSAGE_FORCECONTROL_H
