(cl:defpackage birl_sim_examples-srv
  (:use )
  (:export
   "ADD_GAZEBO_MODEL"
   "<ADD_GAZEBO_MODEL-REQUEST>"
   "ADD_GAZEBO_MODEL-REQUEST"
   "<ADD_GAZEBO_MODEL-RESPONSE>"
   "ADD_GAZEBO_MODEL-RESPONSE"
   "GRIPPER_MOVE"
   "<GRIPPER_MOVE-REQUEST>"
   "GRIPPER_MOVE-REQUEST"
   "<GRIPPER_MOVE-RESPONSE>"
   "GRIPPER_MOVE-RESPONSE"
   "GO_TO_START_POSITION"
   "<GO_TO_START_POSITION-REQUEST>"
   "GO_TO_START_POSITION-REQUEST"
   "<GO_TO_START_POSITION-RESPONSE>"
   "GO_TO_START_POSITION-RESPONSE"
   "GO_TO_POSITION"
   "<GO_TO_POSITION-REQUEST>"
   "GO_TO_POSITION-REQUEST"
   "<GO_TO_POSITION-RESPONSE>"
   "GO_TO_POSITION-RESPONSE"
  ))

