// Generated by gencpp from file example_smach/AddFourInts.msg
// DO NOT EDIT!


#ifndef EXAMPLE_SMACH_MESSAGE_ADDFOURINTS_H
#define EXAMPLE_SMACH_MESSAGE_ADDFOURINTS_H

#include <ros/service_traits.h>


#include <example_smach/AddFourIntsRequest.h>
#include <example_smach/AddFourIntsResponse.h>


namespace example_smach
{

struct AddFourInts
{

typedef AddFourIntsRequest Request;
typedef AddFourIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddFourInts
} // namespace example_smach


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::example_smach::AddFourInts > {
  static const char* value()
  {
    return "0044d017eea346133cfe16eb46e7d664";
  }

  static const char* value(const ::example_smach::AddFourInts&) { return value(); }
};

template<>
struct DataType< ::example_smach::AddFourInts > {
  static const char* value()
  {
    return "example_smach/AddFourInts";
  }

  static const char* value(const ::example_smach::AddFourInts&) { return value(); }
};


// service_traits::MD5Sum< ::example_smach::AddFourIntsRequest> should match 
// service_traits::MD5Sum< ::example_smach::AddFourInts > 
template<>
struct MD5Sum< ::example_smach::AddFourIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::example_smach::AddFourInts >::value();
  }
  static const char* value(const ::example_smach::AddFourIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::example_smach::AddFourIntsRequest> should match 
// service_traits::DataType< ::example_smach::AddFourInts > 
template<>
struct DataType< ::example_smach::AddFourIntsRequest>
{
  static const char* value()
  {
    return DataType< ::example_smach::AddFourInts >::value();
  }
  static const char* value(const ::example_smach::AddFourIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::example_smach::AddFourIntsResponse> should match 
// service_traits::MD5Sum< ::example_smach::AddFourInts > 
template<>
struct MD5Sum< ::example_smach::AddFourIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::example_smach::AddFourInts >::value();
  }
  static const char* value(const ::example_smach::AddFourIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::example_smach::AddFourIntsResponse> should match 
// service_traits::DataType< ::example_smach::AddFourInts > 
template<>
struct DataType< ::example_smach::AddFourIntsResponse>
{
  static const char* value()
  {
    return DataType< ::example_smach::AddFourInts >::value();
  }
  static const char* value(const ::example_smach::AddFourIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // EXAMPLE_SMACH_MESSAGE_ADDFOURINTS_H
