// Generated by gencpp from file point_cloud_selector/SelectCylinderRequest.msg
// DO NOT EDIT!


#ifndef POINT_CLOUD_SELECTOR_MESSAGE_SELECTCYLINDERREQUEST_H
#define POINT_CLOUD_SELECTOR_MESSAGE_SELECTCYLINDERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace point_cloud_selector
{
template <class ContainerAllocator>
struct SelectCylinderRequest_
{
  typedef SelectCylinderRequest_<ContainerAllocator> Type;

  SelectCylinderRequest_()
    : pose()
    , radius(0.0)
    , height(0.0)  {
    }
  SelectCylinderRequest_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , radius(0.0)
    , height(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef double _radius_type;
  _radius_type radius;

   typedef double _height_type;
  _height_type height;




  typedef boost::shared_ptr< ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SelectCylinderRequest_

typedef ::point_cloud_selector::SelectCylinderRequest_<std::allocator<void> > SelectCylinderRequest;

typedef boost::shared_ptr< ::point_cloud_selector::SelectCylinderRequest > SelectCylinderRequestPtr;
typedef boost::shared_ptr< ::point_cloud_selector::SelectCylinderRequest const> SelectCylinderRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace point_cloud_selector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'roscpp': ['/home/ai05/ros_ws/src/ros_comm/clients/roscpp/msg'], 'point_cloud_selector': ['/home/ai05/ros_ws/src/birl_baxter_tools/rviz/point_cloud_selector/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/indigo/share/visualization_msgs/cmake/../msg'], 'tf': ['/opt/ros/indigo/share/tf/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a4e3bfc9767a9507a2a420e39240fa88";
  }

  static const char* value(const ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa4e3bfc9767a9507ULL;
  static const uint64_t static_value2 = 0xa2a420e39240fa88ULL;
};

template<class ContainerAllocator>
struct DataType< ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "point_cloud_selector/SelectCylinderRequest";
  }

  static const char* value(const ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose pose\n\
float64 radius\n\
float64 height\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.radius);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SelectCylinderRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::point_cloud_selector::SelectCylinderRequest_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "radius: ";
    Printer<double>::stream(s, indent + "  ", v.radius);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POINT_CLOUD_SELECTOR_MESSAGE_SELECTCYLINDERREQUEST_H
