// Generated by gencpp from file point_cloud_selector/SetCylinderPropertiesRequest.msg
// DO NOT EDIT!


#ifndef POINT_CLOUD_SELECTOR_MESSAGE_SETCYLINDERPROPERTIESREQUEST_H
#define POINT_CLOUD_SELECTOR_MESSAGE_SETCYLINDERPROPERTIESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/ColorRGBA.h>

namespace point_cloud_selector
{
template <class ContainerAllocator>
struct SetCylinderPropertiesRequest_
{
  typedef SetCylinderPropertiesRequest_<ContainerAllocator> Type;

  SetCylinderPropertiesRequest_()
    : height(0.0)
    , radius(0.0)
    , color()  {
    }
  SetCylinderPropertiesRequest_(const ContainerAllocator& _alloc)
    : height(0.0)
    , radius(0.0)
    , color(_alloc)  {
  (void)_alloc;
    }



   typedef double _height_type;
  _height_type height;

   typedef double _radius_type;
  _radius_type radius;

   typedef  ::std_msgs::ColorRGBA_<ContainerAllocator>  _color_type;
  _color_type color;




  typedef boost::shared_ptr< ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SetCylinderPropertiesRequest_

typedef ::point_cloud_selector::SetCylinderPropertiesRequest_<std::allocator<void> > SetCylinderPropertiesRequest;

typedef boost::shared_ptr< ::point_cloud_selector::SetCylinderPropertiesRequest > SetCylinderPropertiesRequestPtr;
typedef boost::shared_ptr< ::point_cloud_selector::SetCylinderPropertiesRequest const> SetCylinderPropertiesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace point_cloud_selector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'roscpp': ['/home/ai05/ros_ws/src/ros_comm/clients/roscpp/msg'], 'point_cloud_selector': ['/home/ai05/ros_ws/src/birl_baxter_tools/rviz/point_cloud_selector/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/indigo/share/visualization_msgs/cmake/../msg'], 'tf': ['/opt/ros/indigo/share/tf/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "99b58a07a4ea44adc43db01044994e75";
  }

  static const char* value(const ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x99b58a07a4ea44adULL;
  static const uint64_t static_value2 = 0xc43db01044994e75ULL;
};

template<class ContainerAllocator>
struct DataType< ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "point_cloud_selector/SetCylinderPropertiesRequest";
  }

  static const char* value(const ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 height\n\
float64 radius\n\
std_msgs/ColorRGBA color\n\
\n\
================================================================================\n\
MSG: std_msgs/ColorRGBA\n\
float32 r\n\
float32 g\n\
float32 b\n\
float32 a\n\
";
  }

  static const char* value(const ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height);
      stream.next(m.radius);
      stream.next(m.color);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCylinderPropertiesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::point_cloud_selector::SetCylinderPropertiesRequest_<ContainerAllocator>& v)
  {
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "radius: ";
    Printer<double>::stream(s, indent + "  ", v.radius);
    s << indent << "color: ";
    s << std::endl;
    Printer< ::std_msgs::ColorRGBA_<ContainerAllocator> >::stream(s, indent + "  ", v.color);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POINT_CLOUD_SELECTOR_MESSAGE_SETCYLINDERPROPERTIESREQUEST_H
