// Generated by gencpp from file point_cloud_selector/SetCylinderPropertiesResponse.msg
// DO NOT EDIT!


#ifndef POINT_CLOUD_SELECTOR_MESSAGE_SETCYLINDERPROPERTIESRESPONSE_H
#define POINT_CLOUD_SELECTOR_MESSAGE_SETCYLINDERPROPERTIESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace point_cloud_selector
{
template <class ContainerAllocator>
struct SetCylinderPropertiesResponse_
{
  typedef SetCylinderPropertiesResponse_<ContainerAllocator> Type;

  SetCylinderPropertiesResponse_()
    {
    }
  SetCylinderPropertiesResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetCylinderPropertiesResponse_

typedef ::point_cloud_selector::SetCylinderPropertiesResponse_<std::allocator<void> > SetCylinderPropertiesResponse;

typedef boost::shared_ptr< ::point_cloud_selector::SetCylinderPropertiesResponse > SetCylinderPropertiesResponsePtr;
typedef boost::shared_ptr< ::point_cloud_selector::SetCylinderPropertiesResponse const> SetCylinderPropertiesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace point_cloud_selector

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'roscpp': ['/home/ai05/ros_ws/src/ros_comm/clients/roscpp/msg'], 'point_cloud_selector': ['/home/ai05/ros_ws/src/birl_baxter_tools/rviz/point_cloud_selector/msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/indigo/share/visualization_msgs/cmake/../msg'], 'tf': ['/opt/ros/indigo/share/tf/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "point_cloud_selector/SetCylinderPropertiesResponse";
  }

  static const char* value(const ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetCylinderPropertiesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::point_cloud_selector::SetCylinderPropertiesResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // POINT_CLOUD_SELECTOR_MESSAGE_SETCYLINDERPROPERTIESRESPONSE_H
